### ISSUE TITLE
Implement serializable predicate language validator and interpreters

### ISSUE THREAD

**Issue by AlexeyBond** [trilobiitti/trilobite#1]
# Problem

In some cases we need to represent a predicate on set of documents as (in some cases serializable) data. These cases include:

- a client sends a request for certain subset of documents matching a predicate. In this case we need the predicate representation to be serializable as requests are, obviously, serialized.

- server sending a request to database. In this case we need an intermediate representation of filter predicates that can be translated by database drivers to queries in formats specific for database used (e.g. different SQL dialects, MongoDB match queries, etc.). For testing of some high-level functionality we'll also need an in-memory database emulator that may use our intermediate representations of queries directly.

- client subscribing to some events, and server choosing what events should be sent to what clients. In this case the predicate is serialized and sent to server and then somehow be evaluated by the server.

# Suggested solution

Predicates are represented in LISP-like structure. In following examples the structure is represented using JSON. Types used in structure are limited to lists/arrays and strings to provide unambiguity in larger set of serialization methods.

For example, a pseudo-predicate matching articles that were updated and have less than 10 views will look like this:

```JSON
[
  "and",
  ["eq", ["field", "type"], ["str", "Article"]],
  ["gt", ["field", "updatedAt"], ["field", "createdAt"]],
  ["lt", ["field", "views"], ["num", "10"]]
]
```

# Task details

In first iteration the following components should be implemented:

- [ ] Predicate validator. Checks if the given predicate is valid according to configured set of supported functions.
- [ ] Functional predicate interpreter. Creates a function from given predicate representation.
- [ ] Decider predicate interpreter. Creates sets of [DeciderCondition](https://github.com/trilobiitti/trilobite/blob/master/dna/src/commonMain/kotlin/decider.kt#L77)'s that match the documents the predicate is true for.

*Code snippets below are given as reference, some type parameters are missing*

## Predicate functions to implement

- "str" takes string literal, converts to string
- "num" takes string literal, converts to number
- "eq", "ne" - equality/inequality, takes two values, returns boolean
- "in" - takes value and list, returns boolean (`true` iff value is contained in the list)
- "and", "or" - logical and/or operations take variable amount of booleans, return boolean
- "not" - logical negation, takes boolean, returns boolean
- "field" - takes a string literal and returns value of input object field represented by this literal. For validation purposes result should be assumed to be `Any?`

The functions above should be implemented for both validator, functional and decider interpreters, except for "field", which behavior isn't decided yet. For testing purposes (in test sources scope) should be implemented simplified version of it that works with documents of type `BaseReadableDocument<String, Any>` and interprets the field name literal literally (without accessing nested documents when "." found in field name). Simple version of BaseReadableDocument (just a wrapper around a standard `Map`) should also be implemented for interpreters testing.

## General interfaces

Parsed predicate should be represented as

```kotlin
typealias PredicateDefinition = List<Any>

interface PredicateInterpreter<TFunc, TResult>: (PredicateDefinition) -> TResult {
    // Registers a predicate function, returns a function that cancels registration
    fun registerFunction(name: String, function: TFunc): () -> Unit

    // Returns contracts of all registered functions. For validation purposes.
    val functionContracts: Map<String, PredicateFunctionContract>

    // fun invoke(pd: PredicateDefinition): TResult
}

```

'cause it's impossible to describe type `T = [String, ...T] | String` in kotlin.

## Validator

Validator should accept predicate description and set of function descriptions:

```kotlin
sealed class PredicateFunctionInput

class LiteralInput(val literal: String): PredicateFunctionInput
class ValueInput<T>(val type: DataType<T>): PredicateFunctionInput

interface PredicateFunctionContract {
    // Throws if argument types are not acceptable
    // Returns result type if they are
    fun validateArgumentTypes(inputs: List<PredicateFunctionInput>): DataType<*>
}

// Throws if the predicate is not valid
fun validatePredicateDefinition(pd: PredicateDefinition, functions: Map<String, PredicateFunctionContract>) = TODO()

fun validatePredicateDefinition(pd: PredicateDefinition, pi: PredicateInterpreter<*, *>) = validatePredicateDefinition(pd, pi.functionContracts)
```

## Functional interpreter

Potential use case: implementation of filtering operation in a not-so-efficient (but suitable for testing purposes) in-memory storage.

```kotlin
sealed class FunctionalPredicateFunctionInput
class LiteralInput(val value: String): FunctionalPredicateFunctionInput
class FunctionInput(function: (BaseReadableDocument) -> Any)

interface PredicateFunctionImplementation: PredicateFunctionContract {
    fun compile(arguments: List<FunctionalPredicateFunctionInput>): (BaseReadableDocument) -> Any
}

class FunctionalPredicateInterpreter:
    PredicateInterpreter<PredicateFunctionImplementation, (BaseReadableDocument) -> Boolean> {
    // TODO
}
```

## Decider interpreter

Potential use case: a Decider decides, which clients should receive notification on event. A client sends predicate describing set of notifications it wants to receive, we need to transform it into rules for Decider, that can be used to efficiently route the events.

```kotlin
sealed class PredicateDeciderFunctionInput
class LiteralInput(val literal: String): PredicateDeciderFunctionInput
open class VariableInput(val variable: DeciderVariable): PredicateDeciderFunctionInput
class ConstantInput(variable: DeciderVariable, val value: Any): VariableInput(variable)

interface PredicateDeciderFunctionImplementation: PredicateFunctionContract {
    fun toDeciderVariable(inputs: PredicateDeciderFunctionInput): DeciderVariable
}

class DeciderPredicateInterpreter:
    PredicateInterpreter<PredicateDeciderFunctionImplementation, List<List<DecisionCondition<BaseReadableDocument, *>>> {
    // TODO


    // should handle top-level logical operations ("or", "and", "not") and "eq" itself.
    // Logical expressions should be converted to [DNF](https://en.wikipedia.org/wiki/Disjunctive_normal_form)
    // and then list of DecisionCondition's should be created for each conjunction.
    // "eq" uses should be converted to DecisionCondition's, when found under top-level logical operations
    // e.g. for predicate like
    /*
        ["and",
          ["or",
            ["eq", ["field", "a"], ["str", "1"]],
            ["eq", ["field", "b"], ["str", "2"]]
          ],
          ["gt", ["field", "c"], ["num", "3"]]
        ]
    */
    // Two sets of conditions should be generated:
    /*
        [
          DecisionCondition(FieldVar("a"), "1"),
          DecisionCondition(PredicateVariable(FieldVar("c"), { it > 3 }), true)
        ]
        [
          DecisionCondition(FieldVar("b"), "2"),
          DecisionCondition(PredicateVariable(FieldVar("c"), { it > 3 }), true)
        ]
    */
    fun invoke(
        pd: PredicateDefinition,
    ): List<List<DecisionCondition<BaseReadableDocument, *>> = TODO()
}
```
